name: validate

on: 
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [11, 17]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{matrix.version}}
    - name: build
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar:5.6.0.6792 -Dsonar.organization=unknow -Dsonar.projectKey=Unknow0_unknow-maven-codegen 
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}